### ISSUE TITLE
onnx的转化

### ISSUE THREAD

**Issue by XDxiaoqi** [hpc203/M-LSD-onnxrun-cpp-py#1]
冒昧的打扰:
     用您给的onnx文件可以顺利的进行img的推导
     然后用官方代码 https://github.com/lhwcv/mlsd_pytorch.git 用trt_converter.py 进行onnx的转化可顺利进行, 同时
     onnx_model = onnx.load(out_file), onnx.checker.check_model(onnx_model)检查没有问题.
     但是加载自己转化后的onnx文件,加载阶段出现问题如下:

        self.input_name = self.onnx_session.get_inputs()[0].name
        print(" input name is: ", self.input_name)
        #input_name: input_image_with_alpha:0
        #not good: pading0

        self.output_names = [self.onnx_session.get_outputs()[i].name for i in range(3)]
        print(" output name is: ", self.output_names)
        # ['Identity', 'Identity_1', 'Identity_2']
        #not good: list index out of range

    我该如何修改,或者怎么得到您的帮助

**Comment by XDxiaoqi** [comment]
官方的pytorch代码, 模型推导onnx时在不同的文件夹, MobileV2_MLSD的代码不一致所以对应的onnx的init出现问题.
但是面临的新的问题, onnx input_shape是  [1, 3, 512, 512],同时img的data输入是:input_image shape is:  (1, 3, 512, 512)
input_image type is:  float32, 报如下错误:

run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

**Comment by XDxiaoqi** [comment]
参考您的code, export要自己改动一下的,可以正常infer了.感谢

**Comment by ZJDATY** [comment]
> 参考您的code， export要自己改动一下的，可以正常推断了.感谢

能说一下 改动的内容吗？非常感谢。
